import type { Conversation, Message, User, Label } from '@buildpass/shell';

export const mockAgents: User[] = [
  {
    id: '1',
    type: 'human_agent',
    name: 'Fraser Brown',
    email: 'fraserbrown@live.com',
    avatarUrl: null,
  },
  {
    id: '2',
    type: 'human_agent',
    name: 'Joanna Chen',
    email: 'joanna@buildpass.com.au',
    avatarUrl: null,
  },
  {
    id: '3',
    type: 'ai_agent',
    name: 'Ron Swanson',
    email: null,
    avatarUrl: null,
  },
];

export const mockLabels: Label[] = [
  { id: 'l1', name: 'billing', color: '#3b82f6' },
  { id: 'l2', name: 'onboarding', color: '#10b981' },
  { id: 'l3', name: 'bug', color: '#ef4444' },
  { id: 'l4', name: 'feature-request', color: '#8b5cf6' },
];

const contact1: User = {
  id: 'c1',
  type: 'contact',
  name: 'Sarah Mitchell',
  email: 'sarah@acmebuilders.com.au',
  avatarUrl: null,
};

const contact2: User = {
  id: 'c2',
  type: 'contact',
  name: 'Dave Thompson',
  email: 'dave@meridiangroup.com.au',
  avatarUrl: null,
};

const contact3: User = {
  id: 'c3',
  type: 'contact',
  name: 'Lisa Park',
  email: 'lisa.park@constructcorp.com',
  avatarUrl: null,
};

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    displayId: 4521,
    status: 'open',
    channelOrigin: 'email',
    assignee: mockAgents[0]!,
    subject: 'Unable to submit compliance certificate',
    priority: 'high',
    snoozedUntil: null,
    firstReplyAt: '2026-05-08T10:15:00Z',
    resolvedAt: null,
    createdAt: '2026-05-08T09:30:00Z',
    updatedAt: '2026-05-08T14:22:00Z',
    lastMessage: {
      id: 'msg-1-5',
      conversationId: 'conv-1',
      sender: contact1,
      type: 'text',
      visibility: 'public',
      body: 'The form keeps timing out when I try to upload the PDF. I have tried three different browsers.',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-08T14:22:00Z',
      updatedAt: '2026-05-08T14:22:00Z',
    },
    labels: [mockLabels[2]!],
    contact: contact1,
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    displayId: 4520,
    status: 'open',
    channelOrigin: 'web_chat',
    assignee: null,
    subject: null,
    priority: 'medium',
    snoozedUntil: null,
    firstReplyAt: null,
    resolvedAt: null,
    createdAt: '2026-05-08T13:45:00Z',
    updatedAt: '2026-05-08T13:45:00Z',
    lastMessage: {
      id: 'msg-2-1',
      conversationId: 'conv-2',
      sender: contact2,
      type: 'text',
      visibility: 'public',
      body: 'Hi, I am trying to add a new project but the dropdown for certifier is empty. Can someone help?',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-08T13:45:00Z',
      updatedAt: '2026-05-08T13:45:00Z',
    },
    labels: [mockLabels[1]!],
    contact: contact2,
    unreadCount: 1,
  },
  {
    id: 'conv-3',
    displayId: 4519,
    status: 'pending',
    channelOrigin: 'email',
    assignee: mockAgents[1]!,
    subject: 'Invoice query for March',
    priority: 'low',
    snoozedUntil: null,
    firstReplyAt: '2026-05-07T16:00:00Z',
    resolvedAt: null,
    createdAt: '2026-05-07T14:20:00Z',
    updatedAt: '2026-05-07T17:10:00Z',
    lastMessage: {
      id: 'msg-3-3',
      conversationId: 'conv-3',
      sender: mockAgents[1]!,
      type: 'text',
      visibility: 'public',
      body: 'I have forwarded this to our billing team. They should get back to you within 24 hours.',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-07T17:10:00Z',
      updatedAt: '2026-05-07T17:10:00Z',
    },
    labels: [mockLabels[0]!],
    contact: contact3,
    unreadCount: 0,
  },
  {
    id: 'conv-4',
    displayId: 4518,
    status: 'resolved',
    channelOrigin: 'web_chat',
    assignee: mockAgents[2]!,
    subject: 'How to export inspection reports?',
    priority: 'low',
    snoozedUntil: null,
    firstReplyAt: '2026-05-07T10:05:00Z',
    resolvedAt: '2026-05-07T10:30:00Z',
    createdAt: '2026-05-07T10:00:00Z',
    updatedAt: '2026-05-07T10:30:00Z',
    lastMessage: {
      id: 'msg-4-4',
      conversationId: 'conv-4',
      sender: mockAgents[2]!,
      type: 'text',
      visibility: 'public',
      body: 'You can export inspection reports from the Reports tab. Go to Reports > Inspections > Export CSV. Let me know if you need anything else!',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-07T10:30:00Z',
      updatedAt: '2026-05-07T10:30:00Z',
    },
    labels: [],
    contact: contact2,
    unreadCount: 0,
  },
  {
    id: 'conv-5',
    displayId: 4517,
    status: 'snoozed',
    channelOrigin: 'sms',
    assignee: mockAgents[0]!,
    subject: null,
    priority: 'medium',
    snoozedUntil: '2026-05-09T09:00:00Z',
    firstReplyAt: '2026-05-06T15:00:00Z',
    resolvedAt: null,
    createdAt: '2026-05-06T14:30:00Z',
    updatedAt: '2026-05-06T16:00:00Z',
    lastMessage: {
      id: 'msg-5-2',
      conversationId: 'conv-5',
      sender: mockAgents[0]!,
      type: 'text',
      visibility: 'public',
      body: 'Will follow up with you tomorrow morning once I hear back from the team.',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-06T16:00:00Z',
      updatedAt: '2026-05-06T16:00:00Z',
    },
    labels: [mockLabels[3]!],
    contact: contact1,
    unreadCount: 0,
  },
];

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1-1',
      conversationId: 'conv-1',
      sender: contact1,
      type: 'text',
      visibility: 'public',
      body: 'Hi, I am unable to submit the compliance certificate for project BLD-2024-0891. The form keeps timing out.',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-08T09:30:00Z',
      updatedAt: '2026-05-08T09:30:00Z',
    },
    {
      id: 'msg-1-2',
      conversationId: 'conv-1',
      sender: mockAgents[2]!,
      type: 'text',
      visibility: 'internal',
      body: 'Suggestion: This looks like the known file upload timeout issue (BUG-1234). The customer should try reducing the PDF file size to under 10MB, or use the Chrome browser which handles large uploads better.',
      bodyHtml: null,
      metadata: { confidence: 0.85, source: 'knowledge_base' },
      attachments: [],
      createdAt: '2026-05-08T09:31:00Z',
      updatedAt: '2026-05-08T09:31:00Z',
    },
    {
      id: 'msg-1-3',
      conversationId: 'conv-1',
      sender: mockAgents[0]!,
      type: 'text',
      visibility: 'public',
      body: 'Hi Sarah, thanks for reaching out. This is a known issue with large PDF uploads. Could you try reducing the file size to under 10MB? Also, Chrome tends to handle these uploads most reliably.',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-08T10:15:00Z',
      updatedAt: '2026-05-08T10:15:00Z',
    },
    {
      id: 'msg-1-4',
      conversationId: 'conv-1',
      sender: { id: 'system', type: 'system', name: 'System', email: null, avatarUrl: null },
      type: 'activity',
      visibility: 'public',
      body: 'Fraser Brown assigned this conversation to themselves',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-08T10:14:00Z',
      updatedAt: '2026-05-08T10:14:00Z',
    },
    {
      id: 'msg-1-5',
      conversationId: 'conv-1',
      sender: contact1,
      type: 'text',
      visibility: 'public',
      body: 'The form keeps timing out when I try to upload the PDF. I have tried three different browsers.',
      bodyHtml: null,
      metadata: {},
      attachments: [],
      createdAt: '2026-05-08T14:22:00Z',
      updatedAt: '2026-05-08T14:22:00Z',
    },
  ],
};
