export interface EndpointDoc {
  method: string;
  path: string;
  description: string;
  module: string;
}

export const endpointDocs: EndpointDoc[] = [
  { method: 'GET', path: '/api/v1/health', description: 'Health check', module: 'core' },
  { method: 'GET', path: '/api/v1/docs', description: 'This endpoint - list mounted API endpoints', module: 'core' },

  { method: 'POST', path: '/api/v1/auth/verify', description: 'Verify auth token', module: 'identity' },
  { method: 'POST', path: '/api/v1/auth/api-key', description: 'Verify API key', module: 'identity' },
  { method: 'GET', path: '/api/v1/users', description: 'List users', module: 'identity' },
  { method: 'POST', path: '/api/v1/users', description: 'Create a user', module: 'identity' },
  { method: 'GET', path: '/api/v1/users/:id', description: 'Get user by ID', module: 'identity' },
  { method: 'PATCH', path: '/api/v1/users/:id', description: 'Update a user', module: 'identity' },
  { method: 'POST', path: '/api/v1/users/:id/api-key', description: 'Generate a user API key', module: 'identity' },

  { method: 'GET', path: '/api/v1/conversations', description: 'List conversations with filters', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations', description: 'Create a conversation', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/:id', description: 'Get conversation by ID', module: 'conversations' },
  { method: 'PATCH', path: '/api/v1/conversations/:id', description: 'Update a conversation', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/by-number/:displayId', description: 'Get conversation by display number', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/resolve', description: 'Resolve a conversation', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/reopen', description: 'Reopen a conversation', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/pending', description: 'Mark a conversation pending', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/snooze', description: 'Snooze a conversation', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/:id/messages', description: 'List messages for a conversation', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/messages', description: 'Create a message', module: 'conversations' },
  { method: 'GET', path: '/api/v1/messages/search', description: 'Search messages', module: 'conversations' },
  { method: 'GET', path: '/api/v1/messages/:id', description: 'Get message by ID', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/:id/participants', description: 'List conversation participants', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/participants', description: 'Add a participant', module: 'conversations' },
  { method: 'PATCH', path: '/api/v1/conversations/:id/participants/:userId', description: 'Update participant role', module: 'conversations' },
  { method: 'DELETE', path: '/api/v1/conversations/:id/participants/:userId', description: 'Remove a participant', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/assign', description: 'Assign conversation to a user', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/unassign', description: 'Unassign conversation', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/assigned/:userId', description: 'List conversations assigned to a user', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/unassigned', description: 'List unassigned conversations', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/:id/events', description: 'List conversation events', module: 'conversations' },
  { method: 'GET', path: '/api/v1/labels', description: 'List labels', module: 'conversations' },
  { method: 'POST', path: '/api/v1/labels', description: 'Create a label', module: 'conversations' },
  { method: 'GET', path: '/api/v1/conversations/:id/labels', description: 'List conversation labels', module: 'conversations' },
  { method: 'POST', path: '/api/v1/conversations/:id/labels', description: 'Add label to conversation', module: 'conversations' },
  { method: 'DELETE', path: '/api/v1/conversations/:id/labels/:labelId', description: 'Remove label from conversation', module: 'conversations' },
  { method: 'GET', path: '/api/v1/canned-responses', description: 'List canned responses', module: 'conversations' },
  { method: 'POST', path: '/api/v1/canned-responses', description: 'Create canned response', module: 'conversations' },
  { method: 'GET', path: '/api/v1/canned-responses/search', description: 'Search canned responses', module: 'conversations' },
  { method: 'GET', path: '/api/v1/canned-responses/:id', description: 'Get canned response by ID', module: 'conversations' },
  { method: 'PATCH', path: '/api/v1/canned-responses/:id', description: 'Update canned response', module: 'conversations' },
  { method: 'DELETE', path: '/api/v1/canned-responses/:id', description: 'Delete canned response', module: 'conversations' },

  { method: 'GET', path: '/api/v1/channels', description: 'List channels', module: 'channels' },
  { method: 'POST', path: '/api/v1/channels', description: 'Create a channel', module: 'channels' },
  { method: 'GET', path: '/api/v1/channels/:id', description: 'Get channel by ID', module: 'channels' },
  { method: 'PATCH', path: '/api/v1/channels/:id', description: 'Update a channel', module: 'channels' },
  { method: 'DELETE', path: '/api/v1/channels/:id', description: 'Deactivate a channel', module: 'channels' },
  { method: 'POST', path: '/api/v1/widget/conversations', description: 'Start widget conversation', module: 'channels' },
  { method: 'GET', path: '/api/v1/widget/conversations/:id/messages', description: 'Get widget messages', module: 'channels' },
  { method: 'POST', path: '/api/v1/widget/conversations/:id/messages', description: 'Send widget message', module: 'channels' },

  { method: 'GET', path: '/api/v1/agents', description: 'List registered agents', module: 'agents' },
  { method: 'POST', path: '/api/v1/agents', description: 'Register an agent', module: 'agents' },
  { method: 'GET', path: '/api/v1/agents/:id', description: 'Get agent config', module: 'agents' },
  { method: 'PATCH', path: '/api/v1/agents/:id', description: 'Update agent config', module: 'agents' },
  { method: 'GET', path: '/api/v1/conversations/:id/suggestions', description: 'List copilot suggestions', module: 'agents' },
  { method: 'POST', path: '/api/v1/conversations/:id/suggestions/:suggestionId/accept', description: 'Accept copilot suggestion', module: 'agents' },
  { method: 'POST', path: '/api/v1/conversations/:id/suggestions/:suggestionId/dismiss', description: 'Dismiss copilot suggestion', module: 'agents' },
  { method: 'POST', path: '/api/v1/conversations/:id/handoff', description: 'Request handoff', module: 'agents' },
  { method: 'POST', path: '/api/v1/conversations/:id/handoff/agent', description: 'Handoff to an agent', module: 'agents' },

  { method: 'GET', path: '/api/v1/routing-rules', description: 'List routing rules', module: 'routing' },
  { method: 'POST', path: '/api/v1/routing-rules', description: 'Create a routing rule', module: 'routing' },
  { method: 'PATCH', path: '/api/v1/routing-rules/:id', description: 'Update a routing rule', module: 'routing' },
  { method: 'DELETE', path: '/api/v1/routing-rules/:id', description: 'Delete a routing rule', module: 'routing' },
  { method: 'POST', path: '/api/v1/routing-rules/:id/toggle', description: 'Toggle a routing rule', module: 'routing' },
  { method: 'GET', path: '/api/v1/teams', description: 'List teams', module: 'routing' },
  { method: 'POST', path: '/api/v1/teams', description: 'Create a team', module: 'routing' },
  { method: 'GET', path: '/api/v1/teams/:id', description: 'Get team by ID', module: 'routing' },
  { method: 'GET', path: '/api/v1/teams/:id/members', description: 'List team members', module: 'routing' },
  { method: 'POST', path: '/api/v1/teams/:id/members', description: 'Add team member', module: 'routing' },
  { method: 'DELETE', path: '/api/v1/teams/:id/members/:userId', description: 'Remove team member', module: 'routing' },

];
